language: ruby
rvm:
- 2.3.3
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
    - master

sudo: required

before_install:
  - nvm install 6.9.1
  - ruby -v

install:
  - gem install bundler
  - bundle install
  - npm install -g firebase-tools

before_script:
  - jekyll build
  - htmlproofer _site --http-status-ignore "999"

script:
  - firebase use default --token $FIREBASE_DEPLOY_KEY_PROD
  - export COMMIT_HASH=$(echo $TRAVIS_COMMIT | cut -b -6)
  - firebase deploy -m "build $TRAVIS_BUILD_NUMBER $TRAVIS_BRANCH/$COMMIT_HASH" --non-interactive --token $FIREBASE_DEPLOY_KEY_PROD
